---

# Check the requirement for docker specified here: https://docs.docker.com/docker-for-mac/install/
- name: "Check kernel hv support."
  command: "sysctl kern.hv_support"
  register: check_hv_output
  failed_when: check_hv_output.rc != 0
  changed_when: false

- name: "Check system ram is larger than 4G"
  assert:
      that:
            - ansible_memtotal_mb >= 4096

- name: "Check there is no virtualbox lower than 4.3.30 installed"
  shell: "virtualbox --help | head -n 1 | awk '{print $NF}' | sed -e 's/v//'"
  register: check_vb_output
  failed_when: check_vb_output.stdout == "" or check_vb_output.stdout is version('4.3.30', operator='le')
  changed_when: false

# Check the legacy docker-machine environment.
- name: "Check the legacy docker-machine environment variable."
  fail:
      msg: "Please `unset {{ docker_env_var }}` otherwise docker-for-mac can't be installed."
  when: lookup('env', docker_env_var) != ''
  with_items:
      - DOCKER_HOST
      - DOCKER_MACHINE_NAME
      - DOCKER_TLS_VERIFY
      - DOCKER_CERT_PATH
  loop_control:
      loop_var: docker_env_var
