---

- name: "Run os specific checks."
  include_tasks: "{{ item }}"

  with_first_found:
    - files:
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--{{ ansible_distribution_version }}--check.yml"
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--{{ ansible_distribution_major_version }}--check.yml"
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--check.yml"
      skip: true 

- name: "Run os specific tasks."
  include_tasks: "{{ item }}"

  with_first_found:
     - files:
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--{{ ansible_distribution_version }}--apply.yml"
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--{{ ansible_distribution_major_version }}--apply.yml"
        - "{{ role_name }}/tasks/{{ ansible_distribution }}--apply.yml"
       skip: true 

