---

- hosts: dev

  pre_tasks:
    - name: "Check preconditions. Platform: MacOSX, Version: 10.14.5"
      assert:
          that:
              - ansible_distribution == "MacOSX"
              - ansible_distribution_version == "10.14.5"

    # Check the requirement for docker specified here: https://docs.docker.com/docker-for-mac/install/
    - name: "Check kernel hv support."
      command: "sysctl kern.hv_support"
      register: check_output
      failed_when: check_output.rc != 0
      changed_when: false


    - name: "Check system ram is larger than 4G"
      assert:
          that:
                - ansible_memtotal_mb >= 4096

  post_tasks:
      - name: "Display logout warning."
        pause:
            prompt: |
                Finish the owl-setup.
                You may need to restart the computer to enable all changes.
